export const CHANGE_CURRENT_SONG = "play/CHANGE_CURRENT_SONG"
export const CHANGE_PLAY_LIST= "play/CHANGE_PLAY_LIST"
export const CHANGE_CURRENT_SONG_INDEX= "play/CHANGE_CURRENT_SONG_INDEX"

export const CHANGE_SEQUENCE = "player/CHANGE_SEQUENCE";

export const CHANGE_LYRIC_LIST = "player/CHANGE_LYRIC_LIST";
export const CHANGE_CURRENT_LYRIC_INDEX = "player/CHANGE_CURRENT_LYRIC_INDEX";

export const CHANGE_SHOW_PLAYLIST = "player/CHANGE_SHOW_PLAYLIST";

export const CHANGE_SONG_INFO = "player/CHANGE_SONG_INFO";

export const CHANGE_SIMI_PLAYLIST = "player/CHANGE_SIMI_PLAYLIST";
export const CHANGE_SIMI_SONGS = "player/CHANGE_SIMI_SONGS";
